import {useEffect,useRef,useState} from 'react';
import {World,type Projection} from '../scene/World';
import {progress,sceneEnd,stageNames} from '../scene/timeline';
import {panels,specs,swarmFeatures} from '../data/story';
import {goToStage} from '../scene/timeline';
export function SceneView(){const canvas=useRef<HTMLCanvasElement>(null);const [loaded,setLoaded]=useState(false);const [y,setY]=useState(window.scrollY);const [height,setHeight]=useState(innerHeight);const labelRefs=useRef<(HTMLSpanElement|null)[]>([]);const lines=useRef<SVGPolylineElement>(null);
useEffect(()=>{const world=new World(canvas.current!, (p:Projection[])=>{p.forEach((pos,i)=>{const el=labelRefs.current[i];if(el){el.style.transform=`translate(${pos.x}px,${pos.y}px)`;el.style.visibility=pos.visible?'visible':'hidden'}});if(lines.current)lines.current.setAttribute('points',[p[1],p[0],p[2]].map(a=>`${a.x},${a.y}`).join(' '))},()=>setLoaded(true));const scroll=()=>setY(window.scrollY);const resize=()=>setHeight(innerHeight);window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',resize);return()=>{world.dispose();window.removeEventListener('scroll',scroll);window.removeEventListener('resize',resize)}},[]);
const active=panels.find(p=>progress(p.start,y)>=p.from&&(p.end===undefined||progress(p.end,y)<(p.until??0)));const swarm=progress(2,y)>.7&&progress(3,y)<.075;const specsVisible=progress(1,y)>.7&&progress(2,y)<.05;const thermal=progress(6,y)>.98&&progress(7,y)<.02;const visible=y<sceneEnd(height)+height;
return <><div className="scene-spacer" style={{height:sceneEnd(height)+height}}>{stageNames.map((name,i)=><span key={name} id={name}/>)}</div><div className="scene-fixed" style={{visibility:visible?'visible':'hidden',opacity:1-Math.max(0,(y-sceneEnd(height))/(height*.5))}}><canvas ref={canvas} aria-label="Interactive Delta drone mission visualization"/>{!loaded&&<div className="loader"><img src="/assets/images/brand/USAVX_logoMark_white.svg" alt=""/><span>INITIALIZING</span><i/></div>}
{loaded&&active&&<section key={active.start} className={`story-panel ${active.kind??''}`}><div className="story-inner">{active.title&&(active.kind==='hero'?<h1>{active.title}</h1>:<h2>{active.title}{active.badge&&<span className="success-badge">{active.badge}</span>}</h2>)}<div className="story-copy"><p>{active.description}</p>{active.kind==='hero'&&<button className="pill" onClick={()=>goToStage(1)}>Scroll To Explore <span>↓</span></button>}{active.kind==='mission'&&<button className="pill" onClick={()=>goToStage(4)}>Start Mission <span>↓</span></button>}{active.kind==='swarm'&&<div className="feature-table">{swarmFeatures.map(([a,b])=><div key={a}><span>{a}</span><span>{b}</span></div>)}</div>}</div></div></section>}
<div className={'drone-labels '+(swarm?'show':'')}><svg className="connection-lines"><polyline ref={lines} fill="none" stroke="white" strokeWidth=".75" strokeDasharray="3 2.5"/></svg>{[0,1,2].map(i=><span key={i} ref={el=>{labelRefs.current[i]=el}}><b>DSA01{i+1}</b></span>)}</div>
{specsVisible&&<div className="specs-overlay">{specs.map(([title,description],i)=><div className={`spec spec-${i}`} key={title}><h3>{title}</h3><p>{description}</p><i/></div>)}</div>}
{progress(5,y)>.5&&progress(6,y)<.075&&<DetectionBoxes/>}{thermal&&<div className="thermal-label"><span>THERMAL SENSOR</span><div><span>0°C</span><span>148°C</span></div><b>THREAT AREA</b></div>}
{progress(3,y)>.8&&<div className="telemetry" key={Math.floor(y/(height*5))}>{progress(6,y)===0?<>BOOT SEQUENCE…<br/>THERMAL / LIDAR / RGB / IR [ONLINE]<br/>AI: 2 AGENTS / DUAL GPU [ACTIVE]<br/>LINK: PHALANX SYSTEM [ESTABLISHED]<br/><br/>SCAN MODE: ACTIVE<br/>COORD: [37.4419°N / 119.8772°W]<br/>ALT 1,240M | SPEED 74 KM/H</>:<>ALERT: {progress(13,y)>.9?'AREA SECURED':'THERMAL ANOMALY'}<br/>COORD: [37.4478°N / 119.8732°W]<br/>SIG INTENSITY: 87%<br/>{progress(10,y)>.9?'AUTHORITIES CONTACTED':'CLASSIFICATION: POTENTIAL THREAT'}</>}</div>}
</div></>}
function DetectionBoxes(){return <div className="detection-boxes">{Array.from({length:24},(_,i)=><span style={{left:`${(i*37)%90+4}%`,top:`${(i*23)%64+22}%`,width:30+(i%4)*11,height:22+(i%3)*8,animationDelay:`${i*.09}s`}} key={i}><b>{['ROAD BLOCK','POWER LINE','CAR','PERSON','ANTENNA','MOTORCYCLE','ROAD OBSTRUCTION','CAMPFIRE'][i%8]} 99%</b></span>)}</div>}
