import {Group,Mesh,ShaderMaterial,Color,Vector2,Vector3,BufferGeometry,Float32BufferAttribute,Line,LineBasicMaterial,PerspectiveCamera,WebGLRenderer,Scene,PlaneGeometry,Texture} from 'three';
import {CSS3DRenderer,CSS3DObject} from 'three/addons/renderers/CSS3DRenderer.js';import type {GLTF}from'three/addons/loaders/GLTFLoader.js';
import gridVert from '../shaders/grid.vert.glsl?raw';import gridFrag from '../shaders/grid.frag.glsl?raw';import lowVert from '../shaders/lowpoly.vert.glsl?raw';import lowFrag from '../shaders/lowpoly.frag.glsl?raw';import fireVert from '../shaders/sprite.vert.glsl?raw';import fireFrag from '../shaders/fire.frag.glsl?raw';import perimeters from '../data/perimeters.json';import {progress,map,ease}from'./timeline';
type ZoneName=keyof typeof perimeters;
export class MissionLayer{
 readonly group=new Group();private grid=new Group();private map=new Group();private css=new CSS3DRenderer();private zones:{name:ZoneName;object:CSS3DObject;element:HTMLDivElement}[]=[];private dots:{object:CSS3DObject;element:HTMLDivElement}[]=[];private drones:{group:Group;trail:Line;history:Vector3[];index:number}[]=[];private fires:Mesh[]=[];private material:ShaderMaterial;private lowMaterial:ShaderMaterial;
 constructor(scene:Scene,container:HTMLElement,gridModel:GLTF,drone:GLTF,fire:Texture){this.group.position.set(0,-2.5,-8.6);this.map.position.set(0,0,32.15);this.map.rotation.y=Math.PI;this.group.add(this.grid,this.map);scene.add(this.group);this.css.domElement.className='mission-css';this.css.domElement.style.pointerEvents='none';container.append(this.css.domElement);
 this.material=new ShaderMaterial({vertexShader:gridVert,fragmentShader:gridFrag,transparent:true,depthWrite:false,uniforms:{uResolution:{value:new Vector2()},uDpr:{value:1},uHideRatio:{value:0},uGridDensity:{value:3},uOffsetZ:{value:0},uDotSize:{value:.05},uDotOpacity:{value:.1},uLateralFade:{value:.025}}});const geometry=(gridModel.scene.getObjectByName('Plane') as Mesh).geometry;for(const x of [-16,0,16]){const m=new Mesh(geometry,this.material);m.scale.setScalar(.04);m.rotation.y=Math.PI;m.position.set(x,1.2,32);m.renderOrder=1;this.grid.add(m)}
 const zoneData:[ZoneName,number,number,number][]=[['center',-.0475,.56,581],['top-right',5.28,-.53,245],['top-left',-7.04,-.92,240],['bottom-left',-6.545,2.51,250],['bottom-right',8,3.05,200]];
 zoneData.forEach(([name,x,z,width])=>{const d=perimeters[name];const el=document.createElement('div');el.className='mission-zone';el.style.width=width+'px';el.innerHTML=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="-1 -1 ${d.size.width+2} ${d.size.height+2}" fill="none"><path d="${d.path}" fill="#fff" fill-opacity=".05" stroke="#fff" stroke-width="1" vector-effect="non-scaling-stroke"/></svg><span class="zone-status ${d.statusClassName}">◈ SURVEY AREA</span>`;const object=new CSS3DObject(el);object.rotation.x=-Math.PI/2;object.scale.setScalar(.45*.33*3*.025);object.position.set(x,0,z);this.map.add(object);this.zones.push({name,object,element:el})});
 [[1.6,-.35],[-1.15,.2],[1.1,1.7],[5.4,-.72],[-7.09,-1.04],[-6.575,2.46],[7.69,2.26],[8.15,3.3]].forEach(([x,z])=>{const el=document.createElement('div');el.className='mission-dot';el.innerHTML='<i></i><b></b><span></span>';const object=new CSS3DObject(el);object.rotation.x=-Math.PI/2;object.scale.setScalar(.45*.025);object.position.set(x,.01,z);this.map.add(object);this.dots.push({object,element:el})});
 this.lowMaterial=new ShaderMaterial({vertexShader:lowVert,fragmentShader:lowFrag,uniforms:{uColor:{value:new Color('#8a8a8a')},uTime:{value:0}}});const low=(drone.scene.getObjectByName('mainBody') as Mesh).geometry;for(let i=0;i<6;i++){const group=new Group();const mesh=new Mesh(low,this.lowMaterial);mesh.rotation.z=Math.PI;mesh.scale.setScalar(.2);group.add(mesh);const history=Array.from({length:40},()=>new Vector3());const g=new BufferGeometry().setFromPoints(history);const colors=history.flatMap((_,i)=>{const v=(39-i)/39;return[v,v,v]});g.setAttribute('color',new Float32BufferAttribute(colors,3));const trail=new Line(g,new LineBasicMaterial({vertexColors:true,transparent:true,opacity:.8}));trail.renderOrder=2;this.map.add(group,trail);this.drones.push({group,trail,history,index:i})}
 const fmat=new ShaderMaterial({vertexShader:fireVert,fragmentShader:fireFrag,transparent:true,depthWrite:false,uniforms:{uFireTexture:{value:fire},uTime:{value:0},uSpeed:{value:30},uFramesPerRow:{value:8},uTextureColumns:{value:16},uColumnOffset:{value:0},uOffset:{value:0},uOpacity:{value:1},uHideRatio:{value:0},uResolution:{value:new Vector2()}}});[[1.1,1.7],[-1.15,.2],[1.6,-.35]].forEach(([x,z],i)=>{const mesh=new Mesh(new PlaneGeometry(1.2,1.2),fmat.clone());mesh.position.set(x,.3,z);mesh.rotation.x=-Math.PI/2;mesh.renderOrder=4;mesh.material.uniforms.uOffset.value=i*12;this.map.add(mesh);this.fires.push(mesh)})
 }
 update(scene:Scene,camera:PerspectiveCamera,y:number,t:number){const ai=progress(8,y),analysis=progress(9,y),notifications=progress(10,y),coord=progress(11,y),extra=progress(12,y),zone=progress(13,y),multi=progress(14,y);this.material.uniforms.uHideRatio.value=ease(map(ai,0,.5));this.grid.visible=progress(7,y)>.99;this.lowMaterial.uniforms.uTime.value=t;
 this.zones.forEach((z,i)=>{const visible=i===0?ai>.75:i===1?coord>.25:multi>.5;z.element.style.visibility=visible?'visible':'hidden';z.element.style.opacity=visible?'1':'0';const safe=i===0?notifications>.99:i===1?zone>.99:multi>.9;const danger=i===0?analysis===1:i===1?extra>.75:true;const text=i===0?(safe?'Services on site':danger?'Active Threats':'Survey Area'):i===1?(safe?'Area Secured':danger?'Alert Area':'Sensitive Area'):(safe?(i===4?'Area Contained':'Zone Stabilized'):['','','Hazard Area','Active Zone','Alert Area'][i]);const badge=z.element.querySelector('span')!;badge.textContent='◈ '+text.toUpperCase();badge.classList.toggle('safe',safe);badge.classList.toggle('danger',!safe&&danger)});
 this.dots.forEach((d,i)=>{const visible=i<3?ai>.5:i===3?coord>.1:multi>.5;d.element.style.visibility=visible?'visible':'hidden';d.element.classList.toggle('safe',i<3?notifications>.99:i===3?zone>.99:multi>.9);d.element.classList.toggle('danger',i<3?analysis===1&&notifications<.99:i===3?extra>.75&&zone<.99:multi<.9)});
 this.drones.forEach((d,i)=>{const visible=i<2?ai>0:i===2?coord>0:multi>.9;d.group.visible=d.trail.visible=visible;if(!visible)return;let x=0,z=1.25,r=1.5;let p=analysis;if(i===2){x=5.35;z=0;r=1;p=extra}if(i>2){const a=[[-7,-.35],[-6.5,2.9],[8.06,3.16]][i-3];x=a[0];z=a[1];r=1;p=1}const angle=t*.35+(i===1?Math.PI:0);let px=x+Math.cos(angle)*r,pz=z+Math.sin(angle)*r;if(p<1){const initial=i===0?[-7.25,4.89]:i===1?[-11.6,9.08]:[8.72,.76];px=initial[0]+(x-initial[0])*p;pz=initial[1]+(z+(i===0?-1:i===1?1:0)-initial[1])*p}d.group.position.set(px,.8,pz);d.group.rotation.y=-angle;for(let j=39;j>0;j--)d.history[j].copy(d.history[j-1]);d.history[0].copy(d.group.position);d.trail.geometry.setFromPoints(d.history)});
 this.fires.forEach(m=>{m.visible=progress(7,y)>.5&&ai<.5;m.material instanceof ShaderMaterial&&(m.material.uniforms.uTime.value=t,m.material.uniforms.uHideRatio.value=ease(map(ai,0,.5)))});this.css.render(scene,camera)
 }
 resize(w:number,h:number,dpr:number){this.css.setSize(w,h);this.material.uniforms.uResolution.value.set(w*dpr,h*dpr);this.material.uniforms.uDpr.value=dpr;this.fires.forEach(m=>(m.material as ShaderMaterial).uniforms.uResolution.value.set(w*dpr,h*dpr))}
 dispose(){this.css.domElement.remove();this.material.dispose();this.lowMaterial.dispose()}
}
