import {MissionLayer} from './MissionLayer';
import {FlightAudio} from './FlightAudio';
import {WebGLRenderer,Scene,PerspectiveCamera,Color,EquirectangularReflectionMapping,Group,Vector3,Mesh,PlaneGeometry,ShaderMaterial,Vector2,DirectionalLight,AmbientLight,BufferGeometry,Float32BufferAttribute,PointsMaterial,Points,LineBasicMaterial,LineSegments} from 'three';
import {EXRLoader} from 'three/addons/loaders/EXRLoader.js';
import {loadModel,loadTexture} from './assets';
import {CameraRig} from './CameraRig';
import {Drone} from './Drone';
import {Terrain} from './Terrain';
import {PostProcessing} from './PostProcessing';
import {progress,map,sceneEnd,clamp} from './timeline';
import cloudVert from '../shaders/clouds.vert.glsl?raw';
import cloudFrag from '../shaders/clouds.frag.glsl?raw';
export type Projection={x:number;y:number;visible:boolean};
export class World{
 renderer:WebGLRenderer;scene=new Scene();camera=new PerspectiveCamera(20,1,.1,2000);private rig?:CameraRig;private mission?:MissionLayer;private terrain?:Terrain;private drones:Drone[]=[];private post:PostProcessing;private disposed=false;private clouds:Mesh[]=[];private mouse=0;private bank=0;private keys=new Set<string>();private fleet=new Group();private grid=new Group();private last=0;private elapsed=0;private raf=0;private pause=false;private audio=new FlightAudio();
 constructor(private canvas:HTMLCanvasElement,private onProjection:(p:Projection[])=>void,private onReady:()=>void){this.renderer=new WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.scene.background=new Color('#c9e0f7');this.post=new PostProcessing(this.renderer,this.scene,this.camera);window.addEventListener('resize',this.resize);window.addEventListener('pointermove',this.pointer);window.addEventListener('keydown',this.keydown);window.addEventListener('keyup',this.keyup);document.addEventListener('visibilitychange',this.visibility);this.resize();void this.init().catch(e=>{console.error('Scene initialization failed',e);this.onReady()})}
 private pointer=(e:PointerEvent)=>{this.mouse=e.clientX/window.innerWidth*2-1};private keydown=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea'))return;this.keys.add(e.code);if(['ShiftLeft','ArrowLeft','ArrowRight','KeyA','KeyD'].includes(e.code)&&progress(1)<.001)this.audio.start()};private keyup=(e:KeyboardEvent)=>{this.keys.delete(e.code)};private visibility=()=>{this.pause=document.hidden};
 private async init(){const mobile=innerWidth<768;const [terrain,drone,cameraAnim,droneAnim,noise,city,env,gridModel,cityTerrain,lowModel,fire]=await Promise.all([loadModel('terrain'),loadModel('delta-pbr'),loadModel('camera-animations'+(mobile?'-mobile':'')),loadModel('drone-animations'+(mobile?'-mobile':'')),loadTexture('textures/fx/noise.webp',true),loadTexture('textures/terrain/city.webp',false,true),new EXRLoader().loadAsync('/assets/textures/environment/env.exr'),loadModel('grid-city'),loadModel('city-terrain'),loadModel('delta-lowpoly'),loadTexture('textures/fx/fire.webp')]);if(this.disposed)return;env.mapping=EquirectangularReflectionMapping;this.scene.environment=env;
 this.rig=new CameraRig(cameraAnim,droneAnim,mobile);this.rig.group.add(this.camera);this.scene.add(this.rig.group);this.terrain=new Terrain(terrain,noise,city,cityTerrain);this.terrain.group.position.set(0,-2.5,-8.6);this.scene.add(this.terrain.group);this.drones=[0,1,2].map(i=>new Drone(drone,env,noise,i,this.renderer));this.drones.forEach(d=>this.scene.add(d.root));
 const light=new DirectionalLight('#fff',4);light.position.set(-40,100,-30);this.scene.add(light);
 for(let i=0;i<2;i++){const mat=new ShaderMaterial({vertexShader:cloudVert,fragmentShader:cloudFrag,transparent:true,depthWrite:false,uniforms:{uTime:{value:0},uCloudSpeed:{value:.0075*(i+3)},uCloudScale:{value:.1+.2*(i+3)},uCloudDensity:{value:.1+(2-i)*.25},uCloudColor:{value:new Color(1,1,1)},uSunPosition:{value:new Vector3(1,.5,0)},uSkyColor:{value:new Color(.3,.6,1)},uOffset:{value:351+i*247},uFade:{value:1},uZoom:{value:1},uIndex:{value:i+3}}});const mesh=new Mesh(new PlaneGeometry(96,120),mat);mesh.rotation.x=-Math.PI/2;mesh.position.y=-.5-i*.5;mesh.renderOrder=6;this.clouds.push(mesh);this.scene.add(mesh)}
 this.mission=new MissionLayer(this.scene,this.canvas.parentElement!,gridModel,lowModel,fire);
 this.resize();this.onReady();this.raf=requestAnimationFrame(this.frame)}
 private resize=()=>{const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.post.resize(w,h);this.mission?.resize(w,h,this.renderer.getPixelRatio());this.terrain?.resize(w,h,this.renderer.getPixelRatio())};
 private frame=(now:number)=>{this.raf=requestAnimationFrame(this.frame);const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;if(this.pause||this.disposed)return;const y=window.scrollY;if(y>sceneEnd()+innerHeight)return;this.elapsed+=dt;const t=this.elapsed;const p=progress(1,y),swarm=progress(2,y),mission=progress(3,y),flock=progress(4,y),detect=progress(5,y),thermal=progress(6,y),ignition=progress(7,y),ai=progress(8,y);this.rig?.update(y,this.drones.map(d=>d.root));const boost=this.keys.has('ShiftLeft')&&p<.001;this.audio.update(boost,(this.keys.has('ArrowLeft')||this.keys.has('KeyA'))&&p<.001,(this.keys.has('ArrowRight')||this.keys.has('KeyD'))&&p<.001);this.terrain?.update(y,dt,boost);this.scene.background=new Color(ignition>.99?'#000':'#c9e0f7');this.grid.visible=ai>0;this.grid.position.z=-16;this.fleet.visible=flock>.75&&thermal<.01;
 const steering=(Number(this.keys.has('ArrowLeft')||this.keys.has('KeyA'))-Number(this.keys.has('ArrowRight')||this.keys.has('KeyD')));this.bank+=(steering*.3-this.bank)*dt*2;
 this.drones.forEach((d,i)=>{const tm=t+i*1.7;const sway=(.02*Math.sin(.4*tm)+.01*Math.sin(1.1*tm)+.005*Math.sin(2.7*tm))*(i?3:.75);const roll=(.015*Math.sin(.35*tm)+.008*Math.sin(1.2*tm)+.003*Math.sin(2.9*tm))*3;d.root.scale.setScalar(i?(innerWidth<768?(i===1?.004:.0025):.007):map(swarm,0,.5,.0075,.0085)-.001*mission);d.root.visible=(i===0||swarm>0)&&flock<.97;const offset=(i===1?100:i===2?-100:24*swarm)*(1-map(mission,0,.75));d.motion.position.set(offset,sway,(i===2?-100:i===0?24*swarm:0)*(1-map(mission,0,.75))+Math.sin(.5*tm)*7.5*(1-p));d.motion.rotation.z=roll+(i===0?.25*this.mouse*p*(1-swarm)+this.bank*(1-p):0);d.update(t,boost)});
 this.clouds.forEach((m,i)=>{const u=(m.material as ShaderMaterial).uniforms;u.uTime.value=4.5*t+i-1;u.uFade.value=1-ignition});
 this.scene.updateMatrixWorld();this.camera.updateMatrixWorld();this.onProjection(this.drones.map(d=>{const pos=d.motion.getWorldPosition(new Vector3()).project(this.camera);return{x:(pos.x+1)/2*innerWidth,y:(1-pos.y)/2*innerHeight,visible:d.root.visible&&pos.z<1}}));this.mission?.update(this.scene,this.camera,y,t);this.post.render(t,thermal>.98&&ignition<.02?1:0)};
 dispose(){this.disposed=true;cancelAnimationFrame(this.raf);window.removeEventListener('resize',this.resize);window.removeEventListener('pointermove',this.pointer);window.removeEventListener('keydown',this.keydown);window.removeEventListener('keyup',this.keyup);document.removeEventListener('visibilitychange',this.visibility);this.mission?.dispose();this.audio.dispose();this.rig?.dispose();this.terrain?.dispose();this.drones.forEach(d=>d.dispose());this.post.dispose();this.renderer.dispose()}
}
